### ISSUE TITLE
Manifesto completion

### ISSUE THREAD

**Issue by jensr** [ices-eg/wg_WGTAFGOV#1]
### summary
Agreed to complete the text for the manifesto

### task list
- [x] Mission Statement/Aims
- [x] Historical background
- [x] Organisation of TAF repositories
- [x] Sensitive data and data access
- [x] Metadata and publishing
- [x] The system will
- [x] The system will not
- [x] Guidelines for prioritisation / Project management
- [x] Definition of resources available
- [x] Definition of responsibilities
- [ ] Recommendations (move to report)

### related issues

* User handbook #14
* Define a list of repository types and formats #13
* Community involvement in TAF development #17

**Comment by colinpmillar** [comment]
A section on project management would be useful, comment from @pdlynch

**Comment by colinpmillar** [comment]
@colinpmillar 
- [ ] look at sensitive data and metadata section
- [ ] move annex 1 to new issue - add question about metadata for taf types

**Comment by colinpmillar** [comment]
moved metadata description development to #25 and #25

**Comment by nilsolav** [comment]
From: Jens Rasmussen <J.Rasmussen@marlab.ac.uk> 
Sent: fredag 14. januar 2022 10:09
To: Neil Holdsworth <NeilH@ices.dk>; Handegard, Nils Olav <nilsolav@hi.no>
Subject: Re: TAF manifesto

Hi both & happy New Year 

I don't think we have a template for manifestos beyond the heading that were used to shape it in the beginning. But I think it does get edited by secretariat staff for publishing, so I think this was what we discussed? I'm not 100% sure, but I think Ruth is the one coordinating/doing this. 

Thanks,
Jens
________________________________________
From: Neil Holdsworth <NeilH@ices.dk>
Sent: 14 January 2022 09:05:02
To: Nils Olav Handegard; Jens Rasmussen
Subject: RE: TAF manifesto 

Big up for 2022!

Well remembered, but I forget which template it was - @Jens Rasmussen was it to follow the user handbook format? http://community.ices.dk/Publications/UserHandbooks/_layouts/15/start.aspx#/ 

Neil

From: Handegard, Nils Olav <nilsolav@hi.no> 
Sent: 14 January 2022 09:28
To: Jens Rasmussen <J.Rasmussen@marlab.ac.uk>; Neil Holdsworth <NeilH@ices.dk>
Subject: TAF manifesto

Hi Jens/Neil and happy new (covid) year,

At the last TAF meeting you mentioned a template that the manifesto has to follow. Could you please add the link to the template to the “complete manifesto” task?
https://github.com/ices-eg/wg_WGTAFGOV/issues/1

Nils Olav
