### ISSUE TITLE
Develop an working example of populating SAG from TAF

### ISSUE THREAD

**Issue by colinpmillar** [ices-eg/wg_WGTAFGOV#28]
### Summary

Develop a complete pipeline from data to SAG

### task list

- [ ] develop a data format readable by SAG
- [ ] develop a list of metadata records required for the output
- [ ] last publication step

**Comment by iagomosqueira** [comment]
What is missing from what can be already done using something like this:

https://github.com/ices-taf/2020_sol.27.4_forecast/blob/master/output.R#L99

**Comment by colinpmillar** [comment]
Thanks @iagomosqueira! Maybe we can have a quick catch up @Milldaz this afternoon or tomorrow on this?

**Comment by Milldaz** [comment]
Sounds good. Might be worth having @cmspinto there too

**Comment by iagomosqueira** [comment]
Today after WGTAFGOV would be perfect, but any other time is OK.

**Comment by colinpmillar** [comment]
I see this as linked to the work of WKREPTAF which developed a list of standard outputs for a stock assessment project type. I will like to the report when it is published.

**Comment by colinpmillar** [comment]
Had a quick meeting on this and have updated the task list in the issue description

**Comment by colinpmillar** [comment]
Progress is being made on the internal workings (DB and api requirements) here:
https://github.com/ices-taf/doc/issues/277

**Comment by colinpmillar** [comment]
Work is underway on an icesDATSU package to allow users to check and submit files to DATSU (data checking utility and upload)

**Comment by colinpmillar** [comment]
Get comments on the proposal would be appreciated: 
https://github.com/ices-taf/doc/issues/277

@Milldaz @iagomosqueira and anyone else :)

**Comment by iagomosqueira** [comment]
Should we link this to the [FLStock+refpts](https://github.com/flr/FLCore/blob/master/R/FLStockR.R) class? Would everything needed to push to SAG in that class
