### ISSUE TITLE
Keep track of status/needs for data products used as input to the assessments

### ISSUE THREAD

**Issue by nilsolav** [ices-eg/wg_WGTAFGOV#66]
### Summary
Do ICES  have an overview of “data products” by type that is intended to be piped into the assessments? I am thinking of survey indices, catch estimates or any other data input to the assessments? Also, are the calculations scriptable so that we can add it to TAF overview dashboard?

### task list

- [ ] Generate a list of survey indices, catch estimates and other data sets that are used as input in the assessments (if it does not already exist)
- [ ] Add the overview to the dashboard to keep track of TAF progress/wishlist
- [ ] Use this list  so that WGTAFGOV can prioritize implementation, e.g., by type of index.
