### ISSUE TITLE
Transparent Analysis Framework (TAF)

### ISSUE THREAD

**Issue by arni-magnusson** [ices-eg/wg_WGTAFGOV#67]
### Summary

This is a proposal to broaden the definition of the 'A' in TAF from Assessment to Analysis.

It is an idea that Colin and Arni have discussed in the past, as we happily observe TAF being used in increasingly diverse analyses.

The *benefit* of the change is to better reflect the capability and current usage of TAF, which is no longer limited to stock assessments, as was the case when it was named in 2016. The 'assessment' part of the name seems odd and out of context for many current TAF analyses. Even more so when introducing TAF to first-time users who work on analyses that are not assessments.

We suggest a convenient occasion to rename TAF to Transparent Analysis Framework is when we introduce method.R=model.R and boot=bootstrap, which are planned changes for version 4.1.0. Those changes are designed to have a strong backward compatibility support and be interchangeable, especially in the case of method.R=model.R. In the same way, one could say that Transparent Analysis Framework=Transparent Assessment Framework.

There is no need to change old material; we simply start using the term Transparent Analysis Framework more and more, starting with the R package and taf.ices.dk landing page. All current users refer to it as simply 'TAF' and will continue to do so.

We hope that WGTAFGOV does not see any major hurdles going ahead with the renaming, acknowledging the benefits of the new name.

### Task list

- [ ] Discussion at WGTAFGOV
- [ ] Discussion among ICES key people
- [ ] Rename package
- [ ] Change taf.ices.dk landing page
- [ ] Consider other places to gradually implement name change, e.g., user documentation

**Comment by cekv** [comment]
Has been discussed and rejected
